//! `vlpds.space.importRepo` (brief Q8, plan §2.7 "Migration in"): a space
//! repo exported with getRepo comes back in on another host, verified the
//! way `@atproto/space`'s `verifyRepoCarFull` verifies it, keeping its rev,
//! with an empty oplog, and served as it was.
//!
//! - From the reference: testdata/spaces-alpha/export.car, generated by
//!   running the reference's own serializer and signer at 5b95b2f2
//!   (gen-export.mjs), imported mid-migration.
//! - vlpds to vlpds: a member's repo moves between two vlpds hosts with the
//!   account, its blobs following through listMissingBlobs.
//! - Refusals: a tampered CAR, a bad signature or MAC, another DID's or
//!   another space's repo, over `--space-repo-max-records`, a space the
//!   account can't write in, and anything but OAuth. A refused import writes
//!   nothing.
//!
//! importRepo is OAuth-only (brief, FINAL decision 1, option b), and OAuth
//! signs no deactivated account in, so a move imports once the DID points
//! at the new host and the account is active there. The CAR was signed on
//! the old host, so it verifies under the key the DID's PLC history says it
//! held at the commit's rev: the stub directory serves an audit log of
//! every document a test puts in it. An import over a repo that's there
//! replaces it.

use super::phase3::*;
use super::ref_net::*;
use crate::common::spaces::{Holder, SpaceClient};
use crate::common::*;
use crate::oauth;
use axum::extract::{Path, State};
use std::collections::HashMap;
use std::sync::{Arc, Mutex};
use std::time::Duration;

const EXPORT_CAR: &[u8] = include_bytes!("../../../testdata/spaces-alpha/export.car");
const EXPORT_JSON: &str = include_str!("../../../testdata/spaces-alpha/export.json");

pub(crate) type Docs = Arc<Mutex<DocMap>>;

/// Each DID's document, and every one it had as an audit log.
#[derive(Default)]
pub(crate) struct DocMap {
    docs: HashMap<String, J>,
    history: HashMap<String, Vec<J>>,
}

impl DocMap {
    pub fn get(&self, did: &str) -> Option<&J> {
        self.docs.get(did)
    }

    pub fn insert(&mut self, did: String, doc: J) -> Option<J> {
        let key = doc["verificationMethod"]
            .as_array()
            .into_iter()
            .flatten()
            .find(|m| m["id"].as_str().is_some_and(|i| i.ends_with("#atproto")))
            .and_then(|m| m["publicKeyMultibase"].as_str())
            .map(|mb| format!("did:key:{mb}"));
        let at = chrono::Utc::now().to_rfc3339_opts(chrono::SecondsFormat::Micros, true);
        self.history.entry(did.clone()).or_default().push(json!({
            "did": did,
            "operation": {"type": "plc_operation", "verificationMethods": {"atproto": key}},
            "cid": "bafyreie5737gdxlw5i64vzichcalba3z2v5n6icifvx5xytvske7mr3hpm",
            "nullified": false,
            "createdAt": at,
        }));
        self.docs.insert(did, doc)
    }
}

impl DocMap {
    /// Moves every operation in `did`'s audit log `by` into the past, as if
    /// its key rotations happened that much earlier.
    pub fn backdate(&mut self, did: &str, by: Duration) {
        for op in self.history.get_mut(did).into_iter().flatten() {
            let at = chrono::DateTime::parse_from_rfc3339(op["createdAt"].as_str().unwrap()).unwrap();
            let at = at - chrono::Duration::from_std(by).unwrap();
            op["createdAt"] = json!(at.to_rfc3339_opts(chrono::SecondsFormat::Micros, true));
        }
    }
}

/// A PLC directory stand-in serving whatever documents a test puts in it
/// (tests/all/migration.rs's): a DID moves between hosts by a test
/// replacing its document, and `/log/audit` lists each one it had.
pub(crate) async fn stub_plc() -> (String, Docs) {
    let docs: Docs = Arc::default();
    let app = axum::Router::new()
        .route(
            "/{did}",
            axum::routing::get(|State(d): State<Docs>, Path(did): Path<String>| async move {
                match d.lock().unwrap().get(&did) {
                    Some(doc) => Ok(axum::Json(doc.clone())),
                    None => Err(axum::http::StatusCode::NOT_FOUND),
                }
            }),
        )
        .route(
            "/{did}/log/audit",
            axum::routing::get(|State(d): State<Docs>, Path(did): Path<String>| async move {
                match d.lock().unwrap().history.get(&did) {
                    Some(h) => Ok(axum::Json(J::Array(h.clone()))),
                    None => Err(axum::http::StatusCode::NOT_FOUND),
                }
            }),
        )
        .with_state(docs.clone());
    let l = tokio::net::TcpListener::bind("127.0.0.1:0").await.unwrap();
    let url = format!("http://{}", l.local_addr().unwrap());
    tokio::spawn(async move { axum::serve(l, app).await.unwrap() });
    (url, docs)
}

/// A `--spaces` host on the stub directory.
pub(super) async fn stub_host(plc: &str, i: usize) -> TestServer {
    let plc = plc.to_string();
    TestServer::spawn_with(move |c| {
        c.plc_url = plc;
        c.service_did = format!("did:web:pds{i}.test");
        c.spaces = true;
    })
    .await
}

/// Puts `did`'s document, as `s` publishes it, in the directory.
pub(super) async fn publish(docs: &Docs, s: &TestServer, did: &str) {
    let doc = s.xrpc.get("com.atproto.identity.resolveDid", &[("did", did)], &Auth::None).await.ok()["didDoc"].clone();
    docs.lock().unwrap().insert(did.to_string(), doc);
}

/// A [`SpaceClient`] on `s` for an existing account (signed in with
/// `oauth::PASSWORD`), granted `scope`.
pub(super) async fn oauth_client(s: &TestServer, did: &str, handle: &str, jwt: &str, scope: &str) -> SpaceClient {
    let srv = oauth::Srv {
        app: s.app.clone(),
        base: s.url.clone(),
        http: reqwest::Client::builder().redirect(reqwest::redirect::Policy::none()).build().unwrap(),
    };
    let acct = oauth::Account { did: did.into(), handle: handle.into(), jwt: jwt.into() };
    let key = oauth::DpopKey::new();
    let scope = format!("atproto {scope}");
    let t = oauth::grant(&srv, &mut oauth::Browser::default(), &oauth::Flow::loopback(&scope, &key), &acct).await;
    SpaceClient {
        srv,
        did: did.into(),
        handle: handle.into(),
        session_jwt: jwt.into(),
        key,
        access: t.access,
        scope: t.scope,
        holder: Holder::new(),
    }
}

/// An account with an existing DID created on `new` (deactivated until the
/// DID moves), given the old host's service auth for it.
pub(super) struct Arrived {
    pub did: String,
    pub handle: String,
    /// The createAccount session: public methods (not space data).
    pub session: Auth,
}

impl Arrived {
    /// The account's OAuth grant on `new`, once it's active there.
    pub async fn oauth(&self, new: &TestServer) -> SpaceClient {
        let Auth::Bearer(jwt) = &self.session else { unreachable!() };
        oauth_client(new, &self.did, &self.handle, jwt, FULL_SCOPE).await
    }

    /// importRepo on the account's OAuth grant: once it's active.
    pub async fn import(&self, new: &TestServer, space: &str, car: &[u8]) -> Resp {
        import_repo(&self.oauth(new).await, space, car).await
    }
}

pub(super) async fn arrive(new: &TestServer, did: &str, service_auth: String) -> Arrived {
    let handle = format!("{}.{HANDLE_DOMAIN}", unique_name("moved"));
    let body = json!({"handle": handle, "email": format!("{}@example.com", unique_name("moved")), "password": oauth::PASSWORD, "did": did});
    let created = new.xrpc.post("com.atproto.server.createAccount", &body, &Auth::Bearer(service_auth)).await.ok();
    assert_eq!(created["did"], json!(did));
    let jwt = created["accessJwt"].as_str().unwrap().to_string();
    let st = new.xrpc.get("com.atproto.server.checkAccountStatus", &[], &Auth::Bearer(jwt.clone())).await.ok();
    assert_eq!(st["activated"], json!(false), "{st}");
    Arrived { did: did.into(), handle, session: Auth::Bearer(jwt) }
}

/// Points the DID at `new` with the key it recommends, and activates there.
pub(super) async fn complete_move(docs: &Docs, new: &TestServer, a: &Arrived) {
    let rec = new.xrpc.get("com.atproto.identity.getRecommendedDidCredentials", &[], &a.session).await.ok();
    let key = rec["verificationMethods"]["atproto"].as_str().unwrap();
    let doc = json!({
        "@context": ["https://www.w3.org/ns/did/v1"],
        "id": a.did,
        "alsoKnownAs": rec["alsoKnownAs"],
        "verificationMethod": [{
            "id": format!("{}#atproto", a.did), "type": "Multikey", "controller": a.did,
            "publicKeyMultibase": key.strip_prefix("did:key:").unwrap(),
        }],
        "service": [{"id": "#atproto_pds", "type": "AtprotoPersonalDataServer", "serviceEndpoint": new.url}],
    });
    docs.lock().unwrap().insert(a.did.clone(), doc);
    new.xrpc.post_empty("com.atproto.server.activateAccount", &a.session).await.ok();
}

async fn missing_blobs(s: &TestServer, auth: &Auth) -> Vec<String> {
    let r = s.xrpc.get("com.atproto.repo.listMissingBlobs", &[], auth).await.ok();
    r["blobs"].as_array().unwrap().iter().map(|b| b["cid"].as_str().unwrap().to_string()).collect()
}

/// check-space on the account's host checks the imported repo clean.
async fn check_space_ok(s: &TestServer, did: &str, space: &str) {
    let (r, out) = admin_cli(&s.url, &["--json", "check-space", did, space]).await;
    assert!(r.is_ok(), "check-space: {out}");
    let j: J = serde_json::from_str(&out).unwrap();
    assert_eq!(j["ok"], json!(true), "{j}");
}

/// The owner's view of its repo: getLatestCommit's (rev, hash).
async fn head(sc: &SpaceClient, space: &str) -> Option<(String, Vec<u8>)> {
    repo_state(sc, space).await
}

// ---------------------------------------------------------------------------
// the reference's export
// ---------------------------------------------------------------------------

struct Fixture {
    j: J,
    did: String,
    space: String,
    rev: String,
    key: vlsync_atproto::crypto::Keypair,
}

fn fixture() -> Fixture {
    let j: J = serde_json::from_str(EXPORT_JSON).unwrap();
    let key = vlsync_atproto::crypto::Keypair::from_bytes(&hex::decode(j["privateKeyHex"].as_str().unwrap()).unwrap())
        .unwrap();
    assert_eq!(key.did_key(), j["didKey"].as_str().unwrap(), "the fixture's key");
    Fixture {
        did: j["did"].as_str().unwrap().into(),
        space: j["space"].as_str().unwrap().into(),
        rev: j["rev"].as_str().unwrap().into(),
        key,
        j,
    }
}

/// The reference's CAR passes our port of verifyRepoCarFull, and the same
/// commit and records encode back to the same bytes: the reference and
/// vlpds agree on the export format (block order, index encoding, commit
/// encoding), which is what an import reads.
#[test]
fn reference_export_verifies_and_reencodes() {
    let f = fixture();
    let v = verify_repo_car(EXPORT_CAR, &f.space, &f.did, f.j["didKey"].as_str().unwrap(), true)
        .unwrap_or_else(|e| panic!("the reference's export doesn't verify: {e}"));
    assert_eq!(v.commit.rev, f.rev);
    assert_eq!(hex::encode(&v.commit.hash), f.j["hash"].as_str().unwrap());
    let want: Vec<(String, String)> = f.j["records"]
        .as_array()
        .unwrap()
        .iter()
        .map(|r| {
            (
                format!("{}/{}", r["collection"].as_str().unwrap(), r["rkey"].as_str().unwrap()),
                r["cid"].as_str().unwrap().to_string(),
            )
        })
        .collect();
    let mut sorted = want.clone();
    sorted.sort_by(|a, b| vlsync_atproto::cbor::key_cmp(&a.0, &b.0));
    let got: Vec<(String, String)> = v.index.iter().map(|(p, c)| (p.clone(), c.to_string())).collect();
    assert_eq!(got, sorted, "the index, in canonical (length-first) order");
    // the blob is named by a record, as a link
    let blob = f.j["blob"]["cid"].as_str().unwrap();
    assert!(v.records.iter().any(|(_, b)| Value::decode(b).unwrap().to_json().to_string().contains(blob)));

    let (roots, blocks) = vlsync_atproto::car::read_car(EXPORT_CAR).unwrap();
    assert_eq!(commit_block(&v.commit), blocks[0].1, "the commit block re-encodes byte for byte");
    assert_eq!(index_block(&v.index), blocks[1].1, "the index block re-encodes byte for byte");
    let owned: Vec<(Cid, Vec<u8>)> = blocks.iter().map(|(c, b)| (*c, b.to_vec())).collect();
    assert_eq!(write_car(&roots, &owned), EXPORT_CAR, "the CAR framing re-encodes byte for byte");

    // and a commit for another author or space, or a key that isn't the
    // DID's, is refused by the same checks
    let key = f.j["didKey"].as_str().unwrap();
    assert!(verify_repo_car(EXPORT_CAR, &f.space, "did:plc:someoneelse2345abcdefgh", key, true).is_err());
    assert!(verify_repo_car(EXPORT_CAR, &format!("{}x", f.space), &f.did, key, true).is_err());
    let other = vlsync_atproto::crypto::Keypair::generate().did_key();
    assert!(verify_repo_car(EXPORT_CAR, &f.space, &f.did, &other, true).is_err());
}

/// A reference-hosted account moves to vlpds with its space repo: created
/// with its DID, the DID moved and the account activated, then the
/// reference's getRepo CAR imported with OAuth under the key the DID held
/// at its rev (the old host's), the record's blob listed missing until
/// uploaded. vlpds then serves the same repo: the same rev, set hash,
/// index and record blocks, signed by its own key.
#[tokio::test(flavor = "multi_thread", worker_threads = 4)]
async fn reference_export_imports_mid_migration() {
    let f = fixture();
    let (plc, docs) = stub_plc().await;
    let new = stub_host(&plc, 1).await;
    let new_did = new.pds_did().await;
    // the DID's document on the reference host, before the move
    docs.lock().unwrap().insert(
        f.did.clone(),
        json!({
            "@context": ["https://www.w3.org/ns/did/v1"],
            "id": f.did,
            "alsoKnownAs": ["at://refexport.example"],
            "verificationMethod": [{
                "id": format!("{}#atproto", f.did), "type": "Multikey", "controller": f.did,
                "publicKeyMultibase": f.key.did_key().strip_prefix("did:key:").unwrap(),
            }],
            "service": [{"id": "#atproto_pds", "type": "AtprotoPersonalDataServer", "serviceEndpoint": "http://127.0.0.1:9"}],
        }),
    );
    let sa =
        vlpds::auth::service_auth_jwt(&f.key, &f.did, &new_did, Some("com.atproto.server.createAccount"), 60).unwrap();
    let a = arrive(&new, &f.did, sa).await;
    complete_move(&docs, &new, &a).await;
    let oauth = a.oauth(&new).await;

    let out = import_repo(&oauth, &f.space, EXPORT_CAR).await.ok();
    assert_eq!(out["rev"], json!(f.rev), "{out}");
    assert_eq!(out["records"], json!(5), "{out}");
    check_space_ok(&new, &f.did, &f.space).await;

    // the migration copies the record's blob, which listMissingBlobs names
    let blob = f.j["blob"]["cid"].as_str().unwrap().to_string();
    assert_eq!(missing_blobs(&new, &a.session).await, vec![blob.clone()]);
    let bytes = hex::decode(f.j["blob"]["bytesHex"].as_str().unwrap()).unwrap();
    let up = new.xrpc.post_bytes("com.atproto.repo.uploadBlob", bytes, "image/png", &a.session).await.ok();
    assert_eq!(up["blob"]["ref"]["$link"], json!(blob));
    assert!(missing_blobs(&new, &a.session).await.is_empty());
    assert_eq!(head(&oauth, &f.space).await.map(|h| h.0), Some(f.rev.clone()));
    let (_, hash) = head(&oauth, &f.space).await.unwrap();
    assert_eq!(hex::encode(hash), f.j["hash"].as_str().unwrap());
    expect_set_hash_matches_store(&oauth, &f.space).await;
    let r = get_repo_self(&oauth, &f.space).await;
    assert_eq!(r.status, 200, "{}", r.text());
    let mine = verify_repo_car(&r.body, &f.space, &f.did, &did_key(&new, &f.did).await, true)
        .unwrap_or_else(|e| panic!("vlpds's getRepo after the import doesn't verify: {e}"));
    let theirs = verify_repo_car(EXPORT_CAR, &f.space, &f.did, &f.key.did_key(), true).unwrap();
    assert_eq!(
        (mine.commit.rev.clone(), mine.commit.hash.clone()),
        (theirs.commit.rev.clone(), theirs.commit.hash.clone())
    );
    assert_eq!(mine.index_cid, theirs.index_cid, "the same index block");
    assert_eq!(mine.records, theirs.records, "the same record blocks, in the same order");
    let b = dpop_raw(
        &oauth,
        &new.url,
        reqwest::Method::GET,
        "com.atproto.space.getBlob",
        &[("space", &f.space), ("repo", &f.did), ("cid", &blob)],
        None,
    )
    .await;
    assert_eq!((b.status, b.body.to_vec()), (200, hex::decode(f.j["blob"]["bytesHex"].as_str().unwrap()).unwrap()));

    // the oplog starts empty at the imported rev; the next write follows it
    let ops = oauth.get("com.atproto.space.listRepoOps", &[("space", &f.space), ("repo", &f.did)]).await.ok();
    assert_eq!(ops["ops"], json!([]), "{ops}");
    assert_eq!(ops["commit"]["rev"], json!(f.rev), "{ops}");
    let w = write(&oauth, &f.space, W::new().rkey("after-import").text("written on vlpds")).await.ok();
    let (rev, _) = head(&oauth, &f.space).await.unwrap();
    assert!(rev > f.rev, "a write after the import moves past its rev: {rev} vs {}", f.rev);
    assert!(w["uri"].as_str().unwrap().ends_with("/after-import"), "{w}");
    let ops = oauth
        .get("com.atproto.space.listRepoOps", &[("space", &f.space), ("repo", &f.did), ("since", &f.rev)])
        .await
        .ok();
    let mut set = LtHash::default();
    for (p, c) in theirs.set() {
        let (coll, rkey) = p.split_once('/').unwrap();
        set.add(&vlpds::space::commit::element(coll, rkey, &c));
    }
    for op in ops["ops"].as_array().unwrap() {
        super::fuzz::fold(&mut set, op);
    }
    assert!(commit_matches(&set, &ops["commit"]), "the imported set plus the new ops is the head");
    check_space_ok(&new, &f.did, &f.space).await;
}

use vlpds::space::lthash::LtHash;

/// The reference export's record names a blob the new host doesn't hold
/// yet: listMissingBlobs lists it until the migration uploads it.
#[tokio::test(flavor = "multi_thread", worker_threads = 4)]
async fn imported_space_blobs_are_listed_missing() {
    let f = fixture();
    let (plc, docs) = stub_plc().await;
    let new = stub_host(&plc, 1).await;
    let new_did = new.pds_did().await;
    docs.lock().unwrap().insert(
        f.did.clone(),
        json!({
            "@context": ["https://www.w3.org/ns/did/v1"],
            "id": f.did,
            "verificationMethod": [{
                "id": format!("{}#atproto", f.did), "type": "Multikey", "controller": f.did,
                "publicKeyMultibase": f.key.did_key().strip_prefix("did:key:").unwrap(),
            }],
            "service": [{"id": "#atproto_pds", "type": "AtprotoPersonalDataServer", "serviceEndpoint": "http://127.0.0.1:9"}],
        }),
    );
    let sa =
        vlpds::auth::service_auth_jwt(&f.key, &f.did, &new_did, Some("com.atproto.server.createAccount"), 60).unwrap();
    let a = arrive(&new, &f.did, sa).await;
    complete_move(&docs, &new, &a).await;
    a.import(&new, &f.space, EXPORT_CAR).await.ok();
    let blob = f.j["blob"]["cid"].as_str().unwrap().to_string();
    assert_eq!(missing_blobs(&new, &a.session).await, vec![blob]);
}

// ---------------------------------------------------------------------------
// vlpds to vlpds
// ---------------------------------------------------------------------------

/// Two hosts on the stub directory, bob moving from the first to the
/// second; alice governs a space on a third, bob (a member, on the first)
/// writes into it, carol (on the first) reads. The authority isn't on bob's
/// old host: these hosts run with unregistered DIDs, so that host would
/// keep verifying bob by its own document after he left, where a directory
/// host resolves the moved DID.
pub(super) struct TwoHosts {
    pub docs: Docs,
    pub a: TestServer,
    pub b: TestServer,
    /// alice's host.
    pub c: TestServer,
    pub alice: SpaceClient,
    pub bob: SpaceClient,
    pub carol: SpaceClient,
    pub space: String,
}

pub(super) async fn two_hosts() -> TwoHosts {
    let (plc, docs) = stub_plc().await;
    let (a, b, c) = (stub_host(&plc, 0).await, stub_host(&plc, 1).await, stub_host(&plc, 2).await);
    let mut who = Vec::new();
    for (name, host) in [("alice", &c), ("bob", &a), ("carol", &a)] {
        let sc = SpaceClient::new(host, &unique_name(name), FULL_SCOPE).await;
        publish(&docs, host, &sc.did).await;
        who.push(sc);
    }
    let carol = who.pop().unwrap();
    let bob = who.pop().unwrap();
    let alice = who.pop().unwrap();
    let space = format!("at://{}/space/{TEST_SPACE_TYPE}/{}", alice.did, unique_name("mv"));
    let skey = last_segment(&space).to_string();
    let r = alice
        .post(
            "com.atproto.simplespace.createSpace",
            json!({"spaceType": TEST_SPACE_TYPE, "skey": skey, "readPolicy": member_list(), "writePolicy": member_list(), "appAccess": open()}),
        )
        .await;
    assert_eq!(r.ok()["uri"], json!(space));
    for m in [&bob, &carol] {
        put_member(&alice, &space, m, true, true).await.ok();
    }
    TwoHosts { docs, a, b, c, alice, bob, carol, space }
}

/// bob's writes: creates, an update, a delete and a record naming a blob.
/// Returns the blob's CID and bytes.
pub(super) async fn fill_bob(h: &TwoHosts) -> (String, Vec<u8>) {
    for i in 0..6 {
        write(&h.bob, &h.space, W::new().rkey(&format!("r{i}")).text(&format!("bob {i}"))).await.ok();
    }
    put(&h.bob, &h.space, W::new().rkey("r1").text("bob 1, revised")).await.ok();
    del(&h.bob, &h.space, None, "r2").await.ok();
    let bytes = format!("\u{89}PNG\r\n\x1a\n bob's space image {}", unique_name("img")).into_bytes();
    let blob = upload_blob(&h.bob, &bytes).await;
    let rec = json!({"$type": TEST_COLLECTION, "text": "with an image", "image": blob});
    write(&h.bob, &h.space, W::new().rkey("img").record(rec)).await.ok();
    (blob_cid(&blob), bytes)
}

/// bob moves to host b: exported from host a, the DID switched and the
/// account activated on b, then his space repo imported there with his
/// OAuth grant (the first value) and its blobs copied as listMissingBlobs
/// asks.
pub(super) async fn move_bob(h: &TwoHosts, blob: &(String, Vec<u8>)) -> (SpaceClient, VerifiedRepo) {
    let b_did = h.b.pds_did().await;
    let sa = service_jwt(&h.bob, &b_did, "com.atproto.server.createAccount").await;
    let arrived = arrive(&h.b, &h.bob.did, sa).await;
    let r = get_repo_self(&h.bob, &h.space).await;
    assert_eq!(r.status, 200, "{}", r.text());
    let exported = verify_repo_car(&r.body, &h.space, &h.bob.did, &did_key(&h.a, &h.bob.did).await, true).unwrap();
    complete_move(&h.docs, &h.b, &arrived).await;
    let moved = arrived.oauth(&h.b).await;
    let out = import_repo(&moved, &h.space, &r.body).await.ok();
    assert_eq!(out["rev"], json!(exported.commit.rev), "{out}");
    assert_eq!(out["records"], json!(exported.index.len()), "{out}");
    // the blob from the old host's space.getBlob, as the migrate page copies it
    let (status, _, got) = h
        .bob
        .get_raw("com.atproto.space.getBlob", &[("space", &h.space), ("repo", &h.bob.did), ("cid", &blob.0)])
        .await;
    assert_eq!((status, &got), (200, &blob.1));
    assert_eq!(missing_blobs(&h.b, &arrived.session).await, vec![blob.0.clone()]);
    h.b.xrpc.post_bytes("com.atproto.repo.uploadBlob", got, "image/png", &arrived.session).await.ok();
    assert!(missing_blobs(&h.b, &arrived.session).await.is_empty());
    (moved, exported)
}

/// bob's space repo moves from one vlpds host to another with his account:
/// the head (rev and hash), the records, the blob refs and an empty oplog
/// at the imported rev; check-space passes; carol's credential reads the
/// same records from the new host; the authority hears the new host's
/// writes.
#[tokio::test(flavor = "multi_thread", worker_threads = 4)]
async fn vlpds_export_imports_on_another_vlpds() {
    let h = two_hosts().await;
    let blob = fill_bob(&h).await;
    let before = head(&h.bob, &h.space).await.unwrap();
    let cred_a = h.carol_cred().await;
    let records_a = listed(&h.a.url, &cred_a, &h.space, &h.bob.did).await;
    assert_eq!(records_a.len(), 6);

    let (moved, exported) = move_bob(&h, &blob).await;
    let moved = &moved;
    assert_eq!(head(moved, &h.space).await, Some(before.clone()), "the head moves as it was");
    expect_set_hash_matches_store(moved, &h.space).await;
    check_space_ok(&h.b, &h.bob.did, &h.space).await;
    let ops = moved.get("com.atproto.space.listRepoOps", &[("space", &h.space), ("repo", &h.bob.did)]).await.ok();
    assert_eq!(ops["ops"], json!([]), "the oplog starts empty: {ops}");
    assert_eq!(ops["commit"]["rev"], json!(before.0));
    let lb = moved.get("com.atproto.space.listBlobs", &[("space", &h.space), ("repo", &h.bob.did)]).await.ok();
    assert_eq!(lb["cids"], json!([blob.0]), "{lb}");

    h.a.xrpc
        .post("com.atproto.server.deactivateAccount", &json!({}), &Auth::Bearer(h.bob.session_jwt.clone()))
        .await
        .ok();
    let r = get_repo_self(moved, &h.space).await;
    let served = verify_repo_car(&r.body, &h.space, &h.bob.did, &did_key(&h.b, &h.bob.did).await, true)
        .unwrap_or_else(|e| panic!("the new host's getRepo doesn't verify: {e}"));
    assert_eq!(served.index, exported.index);
    assert_eq!(served.records, exported.records);
    assert_eq!((served.commit.rev, served.commit.hash), (exported.commit.rev.clone(), exported.commit.hash.clone()));

    // carol's credential (from the authority on c) reads bob at b
    let cred = h.carol_cred().await;
    assert_eq!(listed(&h.b.url, &cred, &h.space, &h.bob.did).await, records_a);
    let latest =
        cred.get(&h.b.url, "com.atproto.space.getLatestCommit", &[("space", &h.space), ("repo", &h.bob.did)]).await;
    assert_eq!(latest.ok()["commit"]["rev"], json!(before.0));

    // bob writes on b: the authority on c hears the newer rev
    write(moved, &h.space, W::new().rkey("on-b").text("from the new host")).await.ok();
    let (rev, _) = head(moved, &h.space).await.unwrap();
    let mut seen = J::Null;
    for _ in 0..100 {
        seen = cred.get(&h.c.url, "com.atproto.space.listRepos", &[("space", &h.space)]).await.ok();
        let bob = seen["repos"].as_array().unwrap().iter().find(|x| x["did"] == json!(h.bob.did));
        if bob.is_some_and(|b| b["repoRev"] == json!(rev)) {
            break;
        }
        tokio::time::sleep(Duration::from_millis(50)).await;
    }
    let bob = seen["repos"].as_array().unwrap().iter().find(|x| x["did"] == json!(h.bob.did));
    assert_eq!(
        bob.map(|b| &b["repoRev"]),
        Some(&json!(rev)),
        "the authority's listRepos after bob wrote on the new host: {seen}"
    );
    let mut s = Syncer::new(&h.b.url, &h.space, &h.bob.did, &did_key(&h.b, &h.bob.did).await, cred);
    s.full().await;
    let now = listed(&h.b.url, &h.carol_cred().await, &h.space, &h.bob.did).await;
    assert_eq!(now.len(), records_a.len() + 1);
    assert!(records_a.iter().all(|(p, c)| now.get(p) == Some(c)), "{now:?}");
    assert_eq!(s.set, now);
}

impl TwoHosts {
    pub(super) async fn carol_cred(&self) -> Cred {
        let token = delegation_token(&self.carol, &self.space).await;
        let holder = Holder::new();
        let r = exchange(&reqwest::Client::new(), &holder, &self.c.url, &self.space, &token, None).await;
        Cred { credential: r.ok()["credential"].as_str().unwrap().to_string(), holder, http: reqwest::Client::new() }
    }
}

// ---------------------------------------------------------------------------
// imports on one host, and refusals
// ---------------------------------------------------------------------------

/// alice governs a space on one host; bob may write in it.
struct One {
    net: Net,
    alice: SpaceClient,
    bob: SpaceClient,
    space: String,
}

async fn one() -> One {
    let net = Net::new(0).await;
    let (alice, bob) = (net.actor("alice", 0).await, net.actor("bob", 0).await);
    let space = net.create_space(&alice, SpaceOpts { members: &[&bob], ..Default::default() }).await;
    One { net, alice, bob, space }
}

fn records(b: RepoBuilder, n: usize) -> RepoBuilder {
    (0..n).fold(b, |b, i| {
        b.record(TEST_COLLECTION, &format!("imp{i:04}"), record(TEST_COLLECTION, &format!("imported {i}")))
    })
}

async fn nothing_written(sc: &SpaceClient, space: &str, what: &str) {
    assert_eq!(head(sc, space).await, None, "{what}: a refused import wrote a repo");
}

/// A repo bob never wrote here, signed with his own key (a restore from
/// his backup): imported at its rev, served, then written on; the authority
/// sequences it.
#[tokio::test(flavor = "multi_thread", worker_threads = 4)]
async fn imports_a_restored_repo_and_takes_writes_after() {
    let o = one().await;
    let s = &o.net.pds[0];
    let rev = rev_ago(Duration::from_secs(90));
    let b = records(RepoBuilder::new(&o.space, &o.bob.did, &rev), 7);
    let built = b.build(&*account_key(s, &o.bob.did).await);
    let out = import_repo(&o.bob, &o.space, &built.car()).await.ok();
    assert_eq!((out["rev"].clone(), out["records"].clone()), (json!(rev), json!(7)), "{out}");
    assert_eq!(head(&o.bob, &o.space).await, Some((rev.clone(), b.set().digest().to_vec())));
    check_space_ok(s, &o.bob.did, &o.space).await;
    let writers = o.net.await_writer(&o.alice, &o.space, &o.bob.did).await;
    assert!(writers.contains(&o.bob.did), "the authority sequences the imported repo: {writers:?}");

    let cred = o.net.credential_for(&o.alice, &o.space).await;
    let got = listed(&s.url, &cred, &o.space, &o.bob.did).await;
    let want: std::collections::BTreeMap<String, String> =
        built.records.iter().map(|(p, c, _)| (p.clone(), c.to_string())).collect();
    assert_eq!(got, want);
    write(&o.bob, &o.space, W::new().rkey("later").text("after the restore")).await.ok();
    let (after, _) = head(&o.bob, &o.space).await.unwrap();
    assert!(after > rev);
    expect_set_hash_matches_store(&o.bob, &o.space).await;
}

/// The reference's verifyRepoCarFull refuses each of these, and so does
/// the import, writing nothing: a record block whose bytes don't hash to
/// its CID, an index entry naming another CID, a missing record block, an
/// extra block, blocks out of index order, the index before the commit.
#[tokio::test(flavor = "multi_thread", worker_threads = 4)]
async fn refuses_a_tampered_car() {
    let o = one().await;
    let s = &o.net.pds[0];
    let key = account_key(s, &o.bob.did).await;
    let dk = key.did_key();
    let b = records(RepoBuilder::new(&o.space, &o.bob.did, &rev_ago(Duration::from_secs(60))), 4);
    let built = b.build(&key);
    assert!(verify_repo_car(&built.car(), &o.space, &o.bob.did, &dk, true).is_ok());

    let mut cases: Vec<(&str, Vec<u8>)> = vec![
        (
            "a record's bytes changed",
            built.car_with(|bl| bl[3].1 = record_block(&record(TEST_COLLECTION, "tampered")).1),
        ),
        ("a record block missing", built.car_with(|bl| drop(bl.remove(4)))),
        ("an extra block", built.car_with(|bl| bl.push(record_block(&record(TEST_COLLECTION, "extra"))))),
        ("records out of index order", built.car_with(|bl| bl.swap(2, 3))),
        ("the index before the commit", built.car_with(|bl| bl.swap(0, 1))),
    ];
    // an index entry swapped for another record's CID: still a valid block,
    // but it no longer folds to the signed hash
    let mut swapped = built.records.iter().map(|(p, c, _)| (p.clone(), *c)).collect::<Vec<_>>();
    swapped[0].1 = record_block(&record(TEST_COLLECTION, "another")).0;
    let ib = index_block(&swapped);
    let icid = Cid::dag_cbor(&ib);
    let mut blocks = vec![(built.commit_cid, built.commit_block.clone()), (icid, ib)];
    blocks.extend(built.records.iter().map(|(_, c, b)| (*c, b.clone())));
    cases.push(("an index entry naming another CID", write_car(&[built.commit_cid, icid], &blocks)));
    cases.push(("not a CAR", b"not a car at all".to_vec()));
    cases.push(("one root", {
        let all = built.car_with(|_| {});
        let (_, bl) = vlsync_atproto::car::read_car(&all).unwrap();
        let owned: Vec<(Cid, Vec<u8>)> = bl.iter().map(|(c, b)| (*c, b.to_vec())).collect();
        write_car(&[built.commit_cid], &owned)
    }));

    for (what, car) in &cases {
        assert!(
            verify_repo_car(car, &o.space, &o.bob.did, &dk, true).is_err(),
            "{what}: the reference would accept it"
        );
        let r = import_repo(&o.bob, &o.space, car).await;
        assert_eq!(r.status, 400, "{what}: {}", r.text());
        nothing_written(&o.bob, &o.space, what).await;
    }
    import_repo(&o.bob, &o.space, &built.car()).await.ok();
}

/// A commit signed by a key that isn't the DID's, a MAC that doesn't bind
/// the hash, and a hash the records don't fold to are refused.
#[tokio::test(flavor = "multi_thread", worker_threads = 4)]
async fn refuses_a_bad_signature_or_mac() {
    let o = one().await;
    let s = &o.net.pds[0];
    let key = account_key(s, &o.bob.did).await;
    let b = records(RepoBuilder::new(&o.space, &o.bob.did, &rev_ago(Duration::from_secs(60))), 3);

    let wrong_key = b.build(&vlsync_atproto::crypto::Keypair::generate());
    let mut bad_mac = b.build(&key);
    bad_mac.commit.mac[0] ^= 1;
    bad_mac.commit_block = commit_block(&bad_mac.commit);
    bad_mac.commit_cid = Cid::dag_cbor(&bad_mac.commit_block);
    // the MAC rebound to another hash, as anyone holding a commit can: the
    // signature and MAC verify, the index doesn't fold to it
    let mut rebound = b.build(&key);
    let mut other = b.set();
    other.add("com.example.x/y/bafyreie5737gdxlw5i64vzichcalba3z2v5n6icifvx5xytvske7mr3hpm");
    let ctx = vlpds::space::commit::encode_ctx(
        &vlpds::space::commit::CommitCtx { space: &o.space, author: &o.bob.did, rev: &rebound.commit.rev },
        &rebound.commit.ikm,
    )
    .unwrap();
    rebound.commit.hash = other.digest().to_vec();
    rebound.commit.mac = vlpds::space::commit::mac(&rebound.commit.ikm, &ctx, &rebound.commit.hash).to_vec();
    rebound.commit_block = commit_block(&rebound.commit);
    rebound.commit_cid = Cid::dag_cbor(&rebound.commit_block);

    let dk = key.did_key();
    for (what, built) in
        [("another key's signature", wrong_key), ("a broken MAC", bad_mac), ("a rebound hash", rebound)]
    {
        let car = built.car();
        assert!(verify_repo_car(&car, &o.space, &o.bob.did, &dk, true).is_err(), "{what}");
        let r = import_repo(&o.bob, &o.space, &car).await;
        assert_eq!(r.status, 400, "{what}: {}", r.text());
        nothing_written(&o.bob, &o.space, what).await;
    }
}

/// alice's repo (signed by alice for this space) imported by bob, bob's
/// repo for another space imported into this one, and a CAR whose commit
/// names another space are refused.
#[tokio::test(flavor = "multi_thread", worker_threads = 4)]
async fn refuses_another_dids_or_another_spaces_repo() {
    let o = one().await;
    let s = &o.net.pds[0];
    let rev = rev_ago(Duration::from_secs(60));
    let alices = records(RepoBuilder::new(&o.space, &o.alice.did, &rev), 2).build(&*account_key(s, &o.alice.did).await);
    let r = import_repo(&o.bob, &o.space, &alices.car()).await;
    assert_eq!(r.status, 400, "another DID's repo: {}", r.text());
    nothing_written(&o.bob, &o.space, "another DID's repo").await;

    let other = o.net.create_space(&o.alice, SpaceOpts { members: &[&o.bob], ..Default::default() }).await;
    let for_other = records(RepoBuilder::new(&other, &o.bob.did, &rev), 2).build(&*account_key(s, &o.bob.did).await);
    let r = import_repo(&o.bob, &o.space, &for_other.car()).await;
    assert_eq!(r.status, 400, "another space's repo: {}", r.text());
    nothing_written(&o.bob, &o.space, "another space's repo").await;
    // where it belongs, it imports
    import_repo(&o.bob, &other, &for_other.car()).await.ok();
}

/// `--space-repo-max-records` (100k) bounds an import as it bounds writes.
#[tokio::test(flavor = "multi_thread", worker_threads = 4)]
async fn refuses_a_repo_over_the_record_cap() {
    let o = one().await;
    let s = &o.net.pds[0];
    let key = account_key(s, &o.bob.did).await;
    let rev = rev_ago(Duration::from_secs(60));
    let mut b = RepoBuilder::new(&o.space, &o.bob.did, &rev);
    for i in 0..100_001u32 {
        b.records
            .insert(format!("{TEST_COLLECTION}/c{i:06}"), record_block(&json!({"$type": TEST_COLLECTION, "i": i})));
    }
    let car = b.build(&key).car();
    let r = import_repo(&o.bob, &o.space, &car).await;
    refused_mentioning(&r, &["limit", "max"]);
    nothing_written(&o.bob, &o.space, "over the cap").await;
    // at the cap it goes in
    b.records.pop_last();
    import_repo(&o.bob, &o.space, &b.build(&key).car()).await.ok();
}

/// Importing a repo is writing it: an account that isn't a member of the
/// space, or is one without write, is refused as its writes would be, and
/// accepted once the authority lets it write.
#[tokio::test(flavor = "multi_thread", worker_threads = 4)]
async fn refuses_a_space_the_account_cant_write_in() {
    let net = Net::new(0).await;
    let (alice, carol) = (net.actor("alice", 0).await, net.actor("carol", 0).await);
    let space = net.create_space(&alice, SpaceOpts::default()).await;
    let s = &net.pds[0];
    let built = records(RepoBuilder::new(&space, &carol.did, &rev_ago(Duration::from_secs(60))), 2)
        .build(&*account_key(s, &carol.did).await);
    let r = import_repo(&carol, &space, &built.car()).await;
    refused_mentioning(&r, &["member", "not authorized", "forbidden", "write"]);
    nothing_written(&carol, &space, "not a member").await;
    put_member(&alice, &space, &carol, true, false).await.ok();
    let r = import_repo(&carol, &space, &built.car()).await;
    refused_mentioning(&r, &["member", "not authorized", "forbidden", "write"]);
    nothing_written(&carol, &space, "a member without write").await;
    put_member(&alice, &space, &carol, true, true).await.ok();
    import_repo(&carol, &space, &built.car()).await.ok();
}

/// Space data is OAuth-only (brief, FINAL): a password session and app
/// passwords are refused, and an OAuth grant must allow writing in the
/// space.
#[tokio::test(flavor = "multi_thread", worker_threads = 4)]
async fn import_is_oauth_only() {
    let o = one().await;
    let s = &o.net.pds[0];
    let built = records(RepoBuilder::new(&o.space, &o.bob.did, &rev_ago(Duration::from_secs(60))), 2)
        .build(&*account_key(s, &o.bob.did).await);
    let car = built.car();
    let session = Auth::Bearer(o.bob.session_jwt.clone());
    let mut auths = vec![("password session", session.clone())];
    for privileged in [false, true] {
        let ap = s
            .xrpc
            .post(
                "com.atproto.server.createAppPassword",
                &json!({"name": format!("imp-{privileged}"), "privileged": privileged}),
                &session,
            )
            .await
            .ok();
        let sess = s.create_session(&o.bob.did, ap["password"].as_str().unwrap()).await.ok();
        auths.push(("app password", Auth::Bearer(sess["accessJwt"].as_str().unwrap().into())));
    }
    auths.push(("no auth", Auth::None));
    for (what, auth) in &auths {
        let r = import_repo_as(&s.url, auth, &o.space, &car).await;
        assert!(r.status == 401 || r.status == 403, "{what}: {}", r.text());
        nothing_written(&o.bob, &o.space, what).await;
    }
    let read_only = regrant(&o.bob, &format!("space:{TEST_SPACE_TYPE}?authority=*&collection=*&action=read")).await;
    let r = import_repo(&read_only, &o.space, &car).await;
    assert!((400..500).contains(&r.status), "a read-only grant: {}", r.text());
    nothing_written(&o.bob, &o.space, "a read-only grant").await;
    import_repo(&o.bob, &o.space, &car).await.ok();
}

/// After a key rotation the DID's current key is another one: a CAR signed
/// by a key the DID held at the commit's rev (its PLC history) imports, one
/// signed by a key it never had doesn't, and neither does one by a key it
/// held but long before the rev.
#[tokio::test(flavor = "multi_thread", worker_threads = 4)]
async fn import_verifies_against_the_key_held_at_the_rev() {
    let h = two_hosts().await;
    let old_key = account_key(&h.a, &h.bob.did).await;
    let rev = rev_ago(Duration::from_secs(60));
    let built =
        |key: &vlsync_atproto::crypto::Keypair| records(RepoBuilder::new(&h.space, &h.bob.did, &rev), 2).build(key);
    let b_did = h.b.pds_did().await;
    let sa = service_jwt(&h.bob, &b_did, "com.atproto.server.createAccount").await;
    let arrived = arrive(&h.b, &h.bob.did, sa).await;
    complete_move(&h.docs, &h.b, &arrived).await;
    let moved = arrived.oauth(&h.b).await;
    assert_ne!(did_key(&h.b, &h.bob.did).await, old_key.did_key(), "the DID's key rotated");

    let never = built(&vlsync_atproto::crypto::Keypair::generate());
    let r = import_repo(&moved, &h.space, &never.car()).await;
    assert_eq!(r.status, 400, "a key the DID never had: {}", r.text());
    assert_eq!(r.json["error"], json!("InvalidCommit"), "{}", r.text());
    nothing_written(&moved, &h.space, "a key the DID never had").await;

    import_repo(&moved, &h.space, &built(&old_key).car()).await.ok();
    assert_eq!(head(&moved, &h.space).await.map(|h| h.0), Some(rev));
}

/// An import over a repo that's there replaces it with the snapshot at a
/// newer rev, as com.atproto.repo.importRepo does: the old records go, the
/// new ones are served, check-space is clean. The same rev with the same
/// records is a no-op 200 (a retried import); an older rev, or the same
/// rev with other records, is refused, and so is a second import while one
/// runs.
#[tokio::test(flavor = "multi_thread", worker_threads = 4)]
async fn import_over_a_repo_replaces_it() {
    let o = one().await;
    let s = &o.net.pds[0];
    let key = account_key(s, &o.bob.did).await;
    write(&o.bob, &o.space, W::new().rkey("live").text("written here")).await.ok();
    let first = rev_ago(Duration::from_secs(30));
    let mut b = RepoBuilder::new(&o.space, &o.bob.did, &first);
    for i in 0..3 {
        b.records.insert(format!("{TEST_COLLECTION}/old{i}"), record_block(&json!({"$type": TEST_COLLECTION, "i": i})));
    }
    let r = import_repo(&o.bob, &o.space, &b.build(&key).car()).await;
    assert_eq!(r.status, 400, "a rev older than the repo's: {}", r.text());

    let newer = vlsync_atproto::tid::Tid::from_parts(vlsync_atproto::tid::now_micros(), 0).to_string();
    let mut b = RepoBuilder::new(&o.space, &o.bob.did, &newer);
    for i in 0..2 {
        b.records.insert(format!("{TEST_COLLECTION}/new{i}"), record_block(&json!({"$type": TEST_COLLECTION, "n": i})));
    }
    let built = b.build(&key);
    // an import already running holds the space repo
    let sp = s.app.spaces.as_ref().unwrap();
    let sid = vlpds::state::space_id(&o.space);
    assert!(sp.begin_import(&o.bob.did, sid, 7));
    let r = import_repo(&o.bob, &o.space, &built.car()).await;
    assert_eq!(r.status, 400, "a second import: {}", r.text());
    assert!(r.text().contains("in progress"), "{}", r.text());
    sp.end_import(&o.bob.did, sid, 7);

    let out = import_repo(&o.bob, &o.space, &built.car()).await.ok();
    assert_eq!((out["rev"].clone(), out["records"].clone()), (json!(newer), json!(2)), "{out}");
    let mut got: Vec<String> =
        all_records(&o.bob, &o.space).await.iter().map(|r| r["rkey"].as_str().unwrap().to_string()).collect();
    got.sort();
    assert_eq!(got, ["new0", "new1"], "the snapshot replaced the repo");
    assert_eq!(head(&o.bob, &o.space).await.map(|h| h.0), Some(newer.clone()));
    expect_set_hash_matches_store(&o.bob, &o.space).await;
    check_space_ok(s, &o.bob.did, &o.space).await;

    // the same snapshot again (a retried import, signed afresh): a 200 that
    // writes nothing
    o.net.await_writer(&o.alice, &o.space, &o.bob.did).await;
    let p = s.app.partition(&o.bob.did).ok().unwrap();
    let outbox = || p.db.get(vlpds::state::space_outbox_key(&o.bob.did, &sid));
    let ordinal = settled_ordinal(s).await;
    let sp_row = outbox().await.unwrap();
    let again = b.build(&key);
    assert_ne!(again.commit_cid, built.commit_cid, "a fresh signature");
    let out = import_repo(&o.bob, &o.space, &again.car()).await.ok();
    assert_eq!((out["rev"].clone(), out["records"].clone()), (json!(newer), json!(2)), "{out}");
    assert_eq!(s.app.log.next_ordinal(), ordinal, "a same-content import wrote a log segment");
    assert_eq!(outbox().await.unwrap(), sp_row, "a same-content import touched the outbox");
    assert_eq!(head(&o.bob, &o.space).await.map(|h| h.0), Some(newer.clone()));

    // the same rev with other records is refused, and so is an older one
    let mut other = RepoBuilder::new(&o.space, &o.bob.did, &newer);
    other.records.insert(format!("{TEST_COLLECTION}/new0"), record_block(&json!({"$type": TEST_COLLECTION, "n": 9})));
    let r = import_repo(&o.bob, &o.space, &other.build(&key).car()).await;
    assert_eq!(r.status, 400, "the same rev with other records: {}", r.text());
    let r = import_repo(&o.bob, &o.space, &RepoBuilder::new(&o.space, &o.bob.did, &first).build(&key).car()).await;
    assert_eq!(r.status, 400, "an older rev: {}", r.text());
    let mut got: Vec<String> =
        all_records(&o.bob, &o.space).await.iter().map(|r| r["rkey"].as_str().unwrap().to_string()).collect();
    got.sort();
    assert_eq!(got, ["new0", "new1"], "a refused import changed the repo");
}

/// The node log's next ordinal once nothing has been written for 300 ms.
async fn settled_ordinal(s: &TestServer) -> u64 {
    let mut last = s.app.log.next_ordinal();
    for _ in 0..100 {
        tokio::time::sleep(Duration::from_millis(300)).await;
        let now = s.app.log.next_ordinal();
        if now == last {
            return now;
        }
        last = now;
    }
    panic!("the node log never settled");
}

/// A key the DID rotated away from signs only commits from before the
/// rotation (with its 5 min of slack): a former host can't keep minting
/// importable commits after the account left.
#[tokio::test(flavor = "multi_thread", worker_threads = 4)]
async fn a_past_key_signs_only_revs_before_it_was_rotated_away() {
    let h = two_hosts().await;
    let old_key = account_key(&h.a, &h.bob.did).await;
    let b_did = h.b.pds_did().await;
    let sa = service_jwt(&h.bob, &b_did, "com.atproto.server.createAccount").await;
    let arrived = arrive(&h.b, &h.bob.did, sa).await;
    complete_move(&h.docs, &h.b, &arrived).await;
    // the move's rotation, 30 min ago
    h.docs.lock().unwrap().backdate(&h.bob.did, Duration::from_secs(1800));
    let moved = arrived.oauth(&h.b).await;
    let built = |ago: u64| {
        records(RepoBuilder::new(&h.space, &h.bob.did, &rev_ago(Duration::from_secs(ago))), 2).build(&old_key)
    };
    // 20 min ago: after the rotation and its slack
    let r = import_repo(&moved, &h.space, &built(1200).car()).await;
    assert_eq!((r.status, r.json["error"].as_str()), (400, Some("InvalidCommit")), "{}", r.text());
    nothing_written(&moved, &h.space, "a past key after its rotation").await;
    // 27 min ago: within the slack
    let r = import_repo(&moved, &h.space, &built(1620).car()).await;
    assert_eq!(r.status, 200, "{}", r.text());
    // and long before it, but older than what's there now
    let r = import_repo(&moved, &h.space, &built(2400).car()).await;
    assert_eq!(r.status, 400, "{}", r.text());
}

/// A space deleted and made again is a new space: a repo from before
/// (signed by any key the account held then) doesn't come back into it.
#[tokio::test(flavor = "multi_thread", worker_threads = 4)]
async fn a_repo_from_before_the_space_was_made_again_is_refused() {
    let o = one().await;
    let s = &o.net.pds[0];
    let key = account_key(s, &o.alice.did).await;
    let old = records(RepoBuilder::new(&o.space, &o.alice.did, &rev_ago(Duration::from_secs(600))), 2).build(&key);
    write(&o.alice, &o.space, W::new().rkey("live").text("before the delete")).await.ok();
    o.alice.post("com.atproto.simplespace.deleteSpace", json!({"space": o.space})).await.ok();
    let skey = last_segment(&o.space).to_string();
    let again = o
        .alice
        .post(
            "com.atproto.simplespace.createSpace",
            json!({"spaceType": TEST_SPACE_TYPE, "skey": skey, "readPolicy": member_list(), "writePolicy": member_list(), "appAccess": open()}),
        )
        .await;
    assert_eq!(again.ok()["uri"], json!(o.space));
    let r = import_repo(&o.alice, &o.space, &old.car()).await;
    refused_mentioning(&r, &["predates the space"]);
    nothing_written(&o.alice, &o.space, "a repo from before").await;
    // a repo of the space as it is now goes in
    let now = records(RepoBuilder::new(&o.space, &o.alice.did, &rev_ago(Duration::from_secs(1))), 2).build(&key);
    import_repo(&o.alice, &o.space, &now.car()).await.ok();
}

/// The same with the authority on another node of a cluster: the check
/// runs at the owner of the authority's shard, not skipped.
#[tokio::test(flavor = "multi_thread", worker_threads = 8)]
async fn a_repo_from_before_the_space_was_made_again_is_refused_across_a_cluster() {
    let (bucket, plc) = (Arc::new(object_store::memory::InMemory::new()), super::cluster::Plc::start().await);
    let n1 = super::cluster::node("imr-1", &bucket, 6, &plc).await;
    let n2 = super::cluster::node("imr-2", &bucket, 6, &plc).await;
    balanced(&[&n1, &n2]).await;
    let alice = SpaceClient::new(&n1, &unique_name("imra"), FULL_SCOPE).await;
    let bob = SpaceClient::new(&n2, &unique_name("imrb"), FULL_SCOPE).await;
    let make = || async {
        let body = json!({"spaceType": TEST_SPACE_TYPE, "skey": "again", "readPolicy": member_list(), "writePolicy": member_list(), "appAccess": open()});
        let space =
            alice.post("com.atproto.simplespace.createSpace", body).await.ok()["uri"].as_str().unwrap().to_string();
        put_member(&alice, &space, &bob, true, true).await.ok();
        space
    };
    let space = make().await;
    let key = account_key(&n2, &bob.did).await;
    let old = records(RepoBuilder::new(&space, &bob.did, &rev_ago(Duration::from_secs(600))), 2).build(&key);
    alice.post("com.atproto.simplespace.deleteSpace", json!({"space": space})).await.ok();
    assert_eq!(make().await, space);
    let r = import_repo(&bob, &space, &old.car()).await;
    refused_mentioning(&r, &["predates the space"]);
    nothing_written(&bob, &space, "a repo from before, across the cluster").await;
    let now = records(RepoBuilder::new(&space, &bob.did, &rev_ago(Duration::from_secs(1))), 2).build(&key);
    import_repo(&bob, &space, &now.car()).await.ok();
}
