//! The vlpds conformance suite, one test binary (one link for the whole
//! suite). Filter by module: `cargo test --test all crud::` (see
//! tests/STATUS.md).

#![allow(clippy::type_complexity)]

/// Items of `common` that need this suite's own modules (the other test
/// binaries sharing `common` define it to drop them).
macro_rules! suite_only {
    ($($i:item)*) => { $($i)* };
}

mod account;
mod account_counts;
mod account_deactivation;
mod account_races;
mod account_status;
mod account_totals;
mod account_totals_lazy;
mod admin_cli;
mod admin_cluster;
mod admin_proxy;
mod api_mail;
mod app_passwords;
mod auth;
mod auth_caches;
mod backlinks;
mod blob_deletes;
mod blob_gc_race;
mod blobs;
mod bulk_create;
mod cache_caps;
mod cbor_transcode;
mod check_handle;
mod checkpoint_stall;
mod cid_limits;
mod cold_start;
mod commit_cpu;
mod common;
mod compaction_polling;
mod console_api;
mod console_api_accounts;
mod cost_defaults;
mod crawlers;
mod create_post;
mod crud;
mod ctl_shard_move;
mod ctl_takeover;
mod delete_account_retry;
mod differential_shrike;
mod docs_site;
mod dpop_resend;
mod e2e_regressions;
mod email_2fa;
mod email_flows;
mod export_limits;
mod export_order;
mod export_scan;
mod fast_failover;
mod feature_levels;
mod file_uploads;
mod firehose_backfill;
mod firehose_fanout;
mod firehose_shards;
mod firehose_startup;
mod firehose_subscribers;
mod formats;
mod get_blocks_index;
mod go_checker;
mod ha_auth;
mod ha_liveness;
mod handle_domains;
mod handle_validation;
mod handles;
mod harness;
mod identity_races;
mod import_admission;
mod import_bench;
mod import_burst;
mod import_limits;
mod import_stream;
mod imported_blobs;
mod internal_auth;
mod interop_crypto;
mod interop_data_model;
mod interop_mst;
mod interop_syntax;
mod invertible_ops;
mod invite_codes;
mod invites_optional;
mod join_follow;
mod key_rotation;
mod lexicons;
mod link_previews;
mod list_repos_scale;
mod log_pipeline;
mod log_retention;
mod mail_budget;
mod mail_limits;
mod maintenance_coverage;
mod memory_budget;
mod migration;
mod moderation;
mod moderation_console;
mod move_warm;
mod mst_lazy;
mod oauth;
mod oauth_replay_durable;
mod objstore_pressure;
mod ops_metrics;
mod passkeys;
mod peer_tls;
mod plc;
mod preferences;
mod prewarm_limit;
mod proxy;
mod proxy_fast_path;
mod push;
mod races;
mod rate_limit_config;
mod rate_limits;
mod rate_limits_cluster;
mod read_after_write;
mod rebalance_handback;
mod record_encode;
mod ref_account;
mod ref_auth;
mod ref_handles;
mod ref_invites;
mod ref_moderation;
mod ref_moderator_auth;
mod ref_plc;
mod ref_proxy;
mod ref_repo;
mod ref_ssrf;
mod ref_sync;
mod reshard;
mod revocation_gc;
mod revocation_races;
mod scheduled_deletion;
mod secrets_at_rest;
mod segment_bytes;
mod segment_compression;
mod sequencer;
mod server_basics;
mod service_auth;
mod shard_ingest;
mod shrike_adopt;
mod sign_in_security;
mod signature_faults;
mod smtp_mail;
mod spaces;
mod spaces_account_page;
mod spaces_admin;
mod spaces_auth;
mod spaces_blobs;
mod spaces_console;
mod spaces_e2e;
mod spaces_host;
mod spaces_scopes;
mod spaces_side;
mod spaces_sync;
mod staged_import;
mod startup_retry;
mod storage_stats;
mod subscribe_repos;
mod sync;
mod sync11_property;
mod sync_list;
mod takedown_routes;
mod totp;
mod untrusted_repo_data;
mod user_service_auth;
mod vault_transit;
mod web_ui;
#[cfg(feature = "jemalloc")]

/// `--features bench-jemalloc`: the server's allocator, for benches
/// (CPU per op); the suite otherwise runs on the system allocator.
#[cfg(feature = "bench-jemalloc")]
#[global_allocator]
static GLOBAL: tikv_jemallocator::Jemalloc = tikv_jemallocator::Jemalloc;
